version: "3"

services:
  nginx:
    image: nginx:stable
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/certs:/etc/ssl/certs
      - ./nginx/private:/etc/ssl/private
      - ./nginx/static:/var/www/static
    ports:
      - "443:443"
    environment:
      - FAKES_DEPLOY_SERVER_ADDRESS=${FAKES_DEPLOY_SERVER_ADDRESS}
      - API_ADDRESS=api:${API_PORT}

  api:
    build: ./api
    environment:
      - API_ADDRESS=api:${API_PORT}
      - NETWORK_ADDRESS=network:${NETWORK_PORT}
      - LOG_LEVEL=${LOG_LEVEL}
      - COOKIE_STORE_HASH_KEY=${COOKIE_STORE_HASH_KEY}
      - EMAIL_ADDRESS=${EMAIL_ADDRESS}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}

  network:
    build:
      context: ./network
      args:
        - TEXT_DATASET_PATH=${TEXT_DATASET_PATH}
        - TEXT_MODEL_PATH=${TEXT_MODEL_PATH}
        - TEXT_PREPROCESSOR_PATH=${TEXT_PREPROCESSOR_PATH}
    environment:
      - NETWORK_HOST=network
      - NETWORK_PORT=${NETWORK_PORT}
      - TEXT_PREPROCESSOR_PATH=${TEXT_PREPROCESSOR_PATH}
      - TEXT_MODEL_PATH=${TEXT_MODEL_PATH}
      - IMG_MODEL_PATH=${IMG_MODEL_PATH}
      - TEXT_DATASET_PATH=${TEXT_DATASET_PATH}
